#
# TABLE STRUCTURE FOR: ADDRESS
#

DROP TABLE IF EXISTS `ADDRESS`;

CREATE TABLE `ADDRESS` (
  `Address_id` int(11) NOT NULL AUTO_INCREMENT,
  `Customer_id` int(11) DEFAULT NULL,
  `Street` varchar(255) NOT NULL,
  `City` varchar(100) NOT NULL,
  `State` varchar(100) DEFAULT NULL,
  `Zipcode` varchar(10) DEFAULT NULL,
  `Country` varchar(50) NOT NULL,
  PRIMARY KEY (`Address_id`),
  KEY `Customer_id` (`Customer_id`),
  CONSTRAINT `ADDRESS_ibfk_1` FOREIGN KEY (`Customer_id`) REFERENCES `CUSTOMER` (`Customer_id`)
) ENGINE=InnoDB AUTO_INCREMENT=401 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (1, 1, '3143 Lydia Roads', 'Catherineview', 'Indiana', '38994', 'Cook Islands');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (2, 2, '622 Pouros Harbor', 'Lake Saigemouth', 'Nevada', '01452-2676', 'Tunisia');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (3, 3, '37272 Collier Dale Apt. 403', 'Samantamouth', 'Tennessee', '13069-1001', 'United States Virgin Islands');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (4, 4, '8712 Jacynthe Burgs', 'Alizaville', 'Tennessee', '22932', 'Haiti');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (5, 5, '22052 Langosh Well Suite 070', 'Rogahnberg', 'Pennsylvania', '61835', 'Netherlands Antilles');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (6, 6, '3138 Langosh Station Apt. 517', 'New Emeraldview', 'NewMexico', '76865', 'Sudan');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (7, 7, '8364 Pattie Glens Apt. 597', 'New Zariaside', 'Tennessee', '62249-1855', 'Korea');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (8, 8, '3412 Walker Manors', 'Jacobsmouth', 'California', '31380-3180', 'Brazil');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (9, 9, '035 Tromp Harbors', 'Lake Zander', 'Maine', '59134', 'Antarctica (the territory South of 60 deg S)');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (10, 10, '00773 Mertz Pass', 'Kristoffertown', 'NewYork', '05134-5553', 'Liberia');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (11, 11, '978 Hane Dale', 'Williamtown', 'Wyoming', '95885-4780', 'Guernsey');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (12, 12, '049 Cummerata Meadow Suite 645', 'Ebertview', 'Texas', '15292-6975', 'Switzerland');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (13, 13, '5630 Wyman Pine Suite 381', 'Lake Laurianefurt', 'Kansas', '49097', 'Morocco');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (14, 14, '32417 Berry Radial', 'East Oralport', 'Delaware', '45123-3999', 'Sweden');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (15, 15, '881 Marvin Mountains', 'Holdenburgh', 'NewYork', '12867-7010', 'Iceland');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (16, 16, '920 Wunsch Route', 'Stammfort', 'Kentucky', '29417', 'Gambia');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (17, 17, '2375 Steve Drive', 'South Ruthieview', 'Texas', '08289-2145', 'French Polynesia');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (18, 18, '99753 Carter Center Suite 558', 'New Myrlmouth', 'Texas', '27847', 'Bahamas');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (19, 19, '58862 Joseph Locks', 'East Aronburgh', 'Illinois', '36170', 'Fiji');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (20, 20, '7646 Gregg Mountains', 'Lake Pearline', 'Missouri', '73668-0830', 'Lao People\'s Democratic Republic');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (21, 21, '09646 Ollie Extensions Apt. 045', 'Aprilberg', 'Virginia', '60090', 'Hong Kong');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (22, 22, '41892 McDermott Inlet Suite 953', 'South Nestor', 'Arizona', '09883', 'Marshall Islands');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (23, 23, '57740 Hector Hollow', 'New Zanderton', 'Indiana', '74164-0508', 'Monaco');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (24, 24, '9354 Jacobi Plaza Apt. 497', 'O\'Keefeland', 'Maine', '61899-5430', 'Uruguay');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (25, 25, '54932 Balistreri Meadow', 'North Jamaal', 'Vermont', '36946', 'Switzerland');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (26, 26, '107 Lauryn Lock Suite 498', 'East Allie', 'Mississippi', '16214', 'Barbados');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (27, 27, '5107 Eliane Route Suite 816', 'Lake Pabloton', 'Utah', '05594-2125', 'Mali');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (28, 28, '076 Hayes Avenue Apt. 352', 'Port Dustinville', 'Oregon', '66803-3907', 'Mongolia');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (29, 29, '236 Skylar Haven', 'Lake Verner', 'California', '55699', 'Kazakhstan');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (30, 30, '651 Schoen Coves', 'South Eulalia', 'SouthCarolina', '13649-4161', 'Oman');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (31, 31, '674 Skiles Spur', 'Jastchester', 'Pennsylvania', '84640', 'Hong Kong');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (32, 32, '111 Keshaun Gardens Suite 840', 'South Dollyberg', 'Connecticut', '56545-8605', 'Syrian Arab Republic');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (33, 33, '4642 Cassin Port', 'Rosenbaumville', 'NorthCarolina', '70149-0766', 'Algeria');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (34, 34, '79722 Wolff Loaf', 'East Brownchester', 'Wyoming', '20576-0228', 'Slovenia');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (35, 35, '7144 Stanton Forest Apt. 632', 'Louveniaton', 'California', '18978', 'Guatemala');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (36, 36, '3069 Mitchel Run', 'Lake Lane', 'Florida', '40252-1234', 'Jersey');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (37, 37, '6969 Lois Crest', 'Lake Adolfstad', 'Kentucky', '98860', 'French Guiana');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (38, 38, '7717 Mraz Shoals', 'East Arturohaven', 'NewJersey', '55351', 'Monaco');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (39, 39, '7014 Janelle Points Apt. 628', 'West Trever', 'Hawaii', '79536-3686', 'British Virgin Islands');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (40, 40, '595 Feil Dale', 'East Elenoraborough', 'Massachusetts', '54657', 'Togo');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (41, 41, '41807 Maggio Tunnel', 'Hassieside', 'Pennsylvania', '78230-7096', 'Kiribati');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (42, 42, '235 Lorenzo Bridge Suite 495', 'Port Jermainehaven', 'Tennessee', '01896', 'Russian Federation');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (43, 43, '91249 Denesik Radial', 'East Kristofer', 'SouthCarolina', '02439-6705', 'Mauritius');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (44, 44, '82542 Aufderhar Inlet Apt. 468', 'New Rae', 'Wisconsin', '01765-1514', 'Kenya');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (45, 45, '88810 Clement Dam Apt. 383', 'East Corbinview', 'Oklahoma', '85798-7305', 'Oman');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (46, 46, '6886 Jakubowski Pike', 'South Viva', 'Idaho', '98090', 'Guinea-Bissau');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (47, 47, '8017 Michelle Curve', 'Port Tara', 'Minnesota', '95747-4519', 'Barbados');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (48, 48, '1238 McGlynn Ridge', 'Volkmanmouth', 'Oregon', '45076', 'Lithuania');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (49, 49, '81616 Michelle Garden', 'Lake Jovani', 'NewHampshire', '55688-3319', 'French Guiana');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (50, 50, '687 Wehner Crossroad', 'Carterchester', 'Georgia', '76916', 'Saint Barthelemy');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (51, 51, '96119 Rupert Points Suite 914', 'New Kenny', 'Pennsylvania', '96189-9949', 'Russian Federation');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (52, 52, '4191 Stuart Manor', 'Norvalhaven', 'Indiana', '02446', 'Marshall Islands');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (53, 53, '044 Annamarie Court Suite 443', 'North Cathrynbury', 'District of Columbia', '90800-2926', 'Singapore');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (54, 54, '377 Lebsack Place Apt. 294', 'New Natalieborough', 'Georgia', '23137-4704', 'Turkey');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (55, 55, '690 Kunde Motorway Apt. 371', 'Marcborough', 'Oklahoma', '31808', 'Macao');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (56, 56, '76967 Walker Knoll', 'New Paxtonhaven', 'Texas', '66450', 'Serbia');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (57, 57, '421 Hoyt Camp', 'Hirthechester', 'Montana', '99757', 'Norfolk Island');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (58, 58, '2136 Eladio Gateway', 'Xandershire', 'Illinois', '12116-9295', 'Lebanon');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (59, 59, '1421 Beatty Field Apt. 945', 'Kasandramouth', 'RhodeIsland', '00020', 'Tokelau');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (60, 60, '0557 Delphia Grove Apt. 898', 'Joanyport', 'Kentucky', '56940-0036', 'Peru');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (61, 61, '2229 Gorczany Heights', 'Lake Rory', 'Vermont', '78159', 'El Salvador');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (62, 62, '6080 Jasmin Lake Apt. 033', 'Jenkinsburgh', 'Ohio', '71995', 'Syrian Arab Republic');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (63, 63, '0511 Elroy Burg', 'East Elissaberg', 'Nevada', '16805-6070', 'Jordan');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (64, 64, '9165 King Station', 'Spencerburgh', 'Alaska', '40028-9223', 'Croatia');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (65, 65, '9212 Brielle Mission Suite 790', 'Port Ernestinafurt', 'NorthCarolina', '08626-6475', 'Russian Federation');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (66, 66, '079 Kozey Square', 'Jasenberg', 'NorthCarolina', '43376', 'Belarus');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (67, 67, '36818 Marcus Springs', 'Sipesborough', 'Michigan', '81666', 'Tuvalu');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (68, 68, '5393 Liliane Trace', 'Kristatown', 'Maryland', '59754', 'Uganda');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (69, 69, '48837 Connor Crest', 'Jairostad', 'Washington', '50633', 'Trinidad and Tobago');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (70, 70, '13402 Manuela Streets', 'Dibbertport', 'Maryland', '31873', 'Ecuador');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (71, 71, '66566 Eriberto Summit Apt. 513', 'Lake Jewell', 'Vermont', '29237', 'Djibouti');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (72, 72, '9536 Javonte Overpass Suite 254', 'West Jackmouth', 'California', '37746', 'Saint Martin');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (73, 73, '14003 Joesph Grove Suite 584', 'Harberland', 'Iowa', '54746', 'Jamaica');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (74, 74, '141 Strosin Drives', 'Port Rosalinda', 'Delaware', '70602', 'Paraguay');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (75, 75, '9272 Rosenbaum Overpass', 'Darienland', 'Tennessee', '85813-3846', 'Mozambique');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (76, 76, '0134 Rowland Lock', 'Creminberg', 'Missouri', '79265-6052', 'Cote d\'Ivoire');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (77, 77, '6939 Barrows Path', 'Port Mabel', 'Arizona', '05570', 'Belarus');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (78, 78, '7530 Weber Plaza', 'Dietrichborough', 'Colorado', '68699', 'Honduras');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (79, 79, '655 Howe Turnpike Apt. 715', 'Lake Adele', 'Michigan', '28387', 'Sri Lanka');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (80, 80, '728 Salvador Glens Suite 441', 'Adonisfort', 'Alaska', '85801', 'Bangladesh');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (81, 81, '356 Anahi Fords', 'New Ona', 'WestVirginia', '50326', 'Barbados');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (82, 82, '415 Johnston Springs', 'Goldnerfurt', 'Nevada', '71586-7575', 'Serbia');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (83, 83, '6555 Cremin Shore Suite 218', 'Swaniawskiland', 'District of Columbia', '96046', 'Mayotte');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (84, 84, '064 Weimann Causeway', 'South Hillard', 'Nebraska', '10008', 'Svalbard & Jan Mayen Islands');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (85, 85, '5813 Vernice Meadow Apt. 994', 'Beatricestad', 'Missouri', '08759', 'Germany');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (86, 86, '45355 Reichel Crescent', 'West Gwenton', 'Colorado', '10907-2136', 'Dominican Republic');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (87, 87, '76954 Adams Wells', 'South Torey', 'Tennessee', '01924-9166', 'Greenland');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (88, 88, '18288 Bergnaum Club Apt. 675', 'West Eliseo', 'Louisiana', '99724-1121', 'Slovakia (Slovak Republic)');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (89, 89, '086 Gleichner Prairie Apt. 959', 'New Lacey', 'SouthCarolina', '15454', 'United States of America');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (90, 90, '12141 VonRueden Spur Suite 076', 'New Terry', 'NewYork', '44296-6401', 'Nepal');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (91, 91, '185 Andres Causeway Suite 736', 'Earleneburgh', 'Florida', '56869-7081', 'Bosnia and Herzegovina');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (92, 92, '7752 Mae Locks', 'North Dangelo', 'Washington', '75652', 'Christmas Island');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (93, 93, '018 Volkman Prairie', 'Port Tarashire', 'NorthDakota', '27186-9291', 'Gambia');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (94, 94, '2340 McClure Mill Apt. 699', 'Kellitown', 'Louisiana', '48250', 'Moldova');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (95, 95, '7334 D\'Amore Mission', 'Titoport', 'Oregon', '69051', 'Montenegro');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (96, 96, '6853 Friesen Village', 'Buckridgefurt', 'District of Columbia', '82060', 'Chile');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (97, 97, '5067 Cummerata Alley', 'Loyland', 'Illinois', '48266', 'Cook Islands');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (98, 98, '996 Walsh Tunnel Apt. 599', 'Lake Giovanna', 'District of Columbia', '60736', 'Hong Kong');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (99, 99, '705 Satterfield Land Apt. 024', 'Bergstromchester', 'NewMexico', '79983-3592', 'Zambia');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (100, 100, '38326 Mark Street', 'Lefflerville', 'Colorado', '90275', 'French Polynesia');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (101, 101, '48983 Tad Corner Apt. 223', 'Lake Emma', 'Maryland', '13808-5121', 'Egypt');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (102, 102, '32172 Zena Meadow Suite 221', 'New Marlen', 'Oklahoma', '44802', 'Peru');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (103, 103, '97285 Rogahn Place Suite 311', 'Baumbachchester', 'Washington', '34585-9059', 'Guernsey');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (104, 104, '3012 Delfina Pass', 'South Dejonhaven', 'Florida', '94742', 'Aruba');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (105, 105, '443 Fay Streets Suite 669', 'North Berenice', 'Connecticut', '36594', 'Yemen');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (106, 106, '1691 Diana Mills', 'Robbiemouth', 'Delaware', '34182-9371', 'Russian Federation');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (107, 107, '625 Isadore Shoals Apt. 742', 'East Rafael', 'Kentucky', '65107', 'Western Sahara');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (108, 108, '3476 Nicklaus Neck Apt. 648', 'Erikport', 'NewMexico', '60352', 'Saint Pierre and Miquelon');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (109, 109, '05116 Kilback Route', 'Port Sylvanchester', 'NewYork', '84580-5996', 'Nauru');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (110, 110, '79689 Alize Street', 'Port Felipabury', 'NorthCarolina', '64470-2610', 'Costa Rica');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (111, 111, '3517 Pollich Spur', 'South Curtismouth', 'Oklahoma', '57503', 'Northern Mariana Islands');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (112, 112, '55656 Sabina Parkway', 'South Lottieton', 'Missouri', '06703-2033', 'Mauritius');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (113, 113, '34958 Brianne Prairie', 'Littelmouth', 'Michigan', '95036-3474', 'Gambia');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (114, 114, '6136 Rau Place', 'Alyssontown', 'Nevada', '15166', 'Singapore');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (115, 115, '456 Solon Island', 'East Vivianeside', 'RhodeIsland', '05500-6877', 'Colombia');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (116, 116, '135 Fay Ridge', 'Lake Marcellusberg', 'Wyoming', '65878', 'Indonesia');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (117, 117, '6013 Megane Skyway Apt. 176', 'Murrayfort', 'Nevada', '60382-6543', 'Zimbabwe');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (118, 118, '601 Earnestine Motorway Suite 716', 'East Davinstad', 'California', '80766', 'Saint Vincent and the Grenadines');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (119, 119, '47830 Keebler Cape', 'Torphyside', 'WestVirginia', '85193', 'Bahrain');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (120, 120, '4650 Arnulfo Ramp Apt. 602', 'North Keven', 'Virginia', '63747', 'Malta');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (121, 121, '4789 Cory Gateway', 'Volkmanburgh', 'Massachusetts', '76136-4484', 'Haiti');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (122, 122, '853 Modesta Crossroad', 'East Jordane', 'Nebraska', '56073', 'Aruba');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (123, 123, '2626 Hills Mews Apt. 370', 'South Jaida', 'Virginia', '04807', 'Gabon');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (124, 124, '5550 Krajcik Rapids', 'Port Felipe', 'Indiana', '50742-7496', 'Syrian Arab Republic');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (125, 125, '8412 Leuschke Parks', 'Flavioton', 'NewJersey', '87785-8593', 'Saint Martin');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (126, 126, '3408 Huel Springs Apt. 922', 'North Donnaport', 'NorthDakota', '94661', 'Norway');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (127, 127, '6152 Kuphal Union Suite 135', 'North Nayeliview', 'Arizona', '01645-5822', 'Denmark');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (128, 128, '219 Stark Motorway', 'South Lester', 'Nevada', '82690', 'Iceland');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (129, 129, '2336 Emard Orchard Apt. 967', 'Alexandraville', 'Michigan', '90335', 'Chile');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (130, 130, '48762 Shanahan Walk Suite 794', 'Dejahfurt', 'Idaho', '67145-7381', 'Australia');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (131, 131, '93479 Virgie Loaf', 'Starktown', 'Connecticut', '74806', 'Dominican Republic');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (132, 132, '8361 Casimer Spring', 'South Cade', 'Texas', '68835', 'Belgium');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (133, 133, '0676 Bruen Knolls', 'Spinkaport', 'Wyoming', '73956-5693', 'Qatar');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (134, 134, '89948 Madonna Skyway', 'Olsonburgh', 'Mississippi', '06690-7552', 'Bahrain');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (135, 135, '39061 Alyson Squares Apt. 598', 'East Friedrich', 'Oklahoma', '65836-6730', 'Bolivia');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (136, 136, '998 Adams Plain', 'Lake Naomie', 'Arkansas', '72350-6017', 'Martinique');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (137, 137, '535 Halvorson Cape', 'Lake Nichole', 'Pennsylvania', '84471', 'Botswana');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (138, 138, '8822 Wisozk Tunnel Apt. 247', 'Romanfurt', 'Florida', '59266', 'Tonga');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (139, 139, '218 Tremblay Oval', 'South Loyceberg', 'Hawaii', '31816-6397', 'Benin');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (140, 140, '2691 Rolfson Orchard Apt. 730', 'North Seanborough', 'Ohio', '88307', 'French Southern Territories');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (141, 141, '2728 Kaleb Place Apt. 446', 'West Casimer', 'Arizona', '22965-4766', 'Mauritius');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (142, 142, '52580 Abelardo Ferry Suite 271', 'Friesenmouth', 'NewHampshire', '37226', 'Greenland');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (143, 143, '4508 Kenyon Walks Apt. 797', 'Christopville', 'Minnesota', '92504-2333', 'Djibouti');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (144, 144, '063 Kuhic Villages Suite 909', 'West Merlinside', 'Pennsylvania', '48091', 'Saint Helena');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (145, 145, '6543 Reichert Brooks', 'East Guido', 'NewHampshire', '65075', 'United States Minor Outlying Islands');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (146, 146, '07175 Sandrine Center Apt. 316', 'East Theresiaside', 'Massachusetts', '22292', 'Kazakhstan');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (147, 147, '654 Dayton Fords Apt. 433', 'South Zolamouth', 'WestVirginia', '42637-9802', 'San Marino');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (148, 148, '61549 Felicia Prairie', 'Talonside', 'Oregon', '35653', 'Anguilla');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (149, 149, '989 Howell Drives', 'Kianaberg', 'Nebraska', '07178-5055', 'Kuwait');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (150, 150, '233 Coleman Ports', 'Mayertmouth', 'Ohio', '01698', 'Sweden');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (151, 151, '10275 Shemar Trace', 'Rafaelmouth', 'WestVirginia', '11290', 'Bosnia and Herzegovina');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (152, 152, '333 Hirthe Drive Suite 715', 'Obieville', 'Delaware', '74467-1522', 'Saudi Arabia');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (153, 153, '0211 Alda Rue Suite 987', 'Farrellberg', 'Alaska', '63239-6390', 'Korea');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (154, 154, '413 Keeling Creek', 'New Bridgetstad', 'Tennessee', '16810-7681', 'Western Sahara');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (155, 155, '5788 Asa Road Apt. 703', 'Schaefermouth', 'SouthCarolina', '58544-7491', 'Angola');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (156, 156, '61482 Stehr Motorway', 'Murrayton', 'Washington', '56031', 'Malta');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (157, 157, '83642 Rodriguez Rapid', 'Leannonfort', 'NewMexico', '20312-1769', 'Botswana');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (158, 158, '80247 Macy Creek', 'Austinchester', 'Alaska', '66037', 'Liechtenstein');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (159, 159, '75182 Deion Grove', 'East Colten', 'Wisconsin', '40202-0266', 'New Caledonia');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (160, 160, '366 Reta Port Apt. 626', 'North Christine', 'District of Columbia', '84324-8896', 'Senegal');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (161, 161, '153 Bosco Station Suite 144', 'Schuppeville', 'Maine', '22719-0688', 'Turkey');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (162, 162, '862 Jasen Mission Apt. 750', 'Lebsackhaven', 'SouthDakota', '75246-7822', 'Lao People\'s Democratic Republic');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (163, 163, '939 Lurline Springs', 'Tateshire', 'Arizona', '96524', 'Tajikistan');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (164, 164, '61440 Jasper Freeway', 'Port Gregg', 'Nebraska', '81221', 'India');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (165, 165, '1618 Arnoldo Circle Suite 952', 'East Bridgettehaven', 'Nebraska', '44279-9753', 'Niue');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (166, 166, '515 Koss Shoals', 'West Talon', 'Washington', '08111-3069', 'Zambia');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (167, 167, '8272 Marjory Avenue Suite 338', 'East Elouiseton', 'NorthDakota', '54206-2780', 'Denmark');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (168, 168, '416 Hamill Ferry Suite 582', 'Christianatown', 'Idaho', '67250', 'Senegal');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (169, 169, '48849 Kassulke Square Apt. 878', 'Lake Cheyanne', 'Montana', '60593', 'Nigeria');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (170, 170, '7064 Carlie Stravenue', 'Kovacekfurt', 'SouthDakota', '32555-3613', 'Libyan Arab Jamahiriya');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (171, 171, '41668 Bart Rapids', 'New Reuben', 'NewMexico', '50743', 'Central African Republic');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (172, 172, '7497 Ratke Mountains Suite 326', 'Port Royce', 'NorthDakota', '63865', 'Dominican Republic');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (173, 173, '507 Vernice Squares', 'New Harley', 'Utah', '91571-2155', 'Sao Tome and Principe');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (174, 174, '472 Jaylon Motorway Suite 661', 'Dibbertshire', 'Utah', '89759', 'Belize');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (175, 175, '04470 Hettinger Inlet', 'North Noreneview', 'Georgia', '73549-9891', 'Australia');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (176, 176, '169 Emard Viaduct', 'Chanelletown', 'Oklahoma', '39452-8767', 'Bahamas');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (177, 177, '45366 Ernie Underpass', 'New Geovannihaven', 'NewJersey', '17403-4392', 'Botswana');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (178, 178, '82482 Dickinson Mission Suite 593', 'South Pierre', 'Colorado', '43393-0438', 'Mexico');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (179, 179, '5636 Kuhn Ridges Apt. 842', 'Kuhichaven', 'Utah', '37573', 'Denmark');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (180, 180, '698 Fay Crest Apt. 400', 'West Ernie', 'Nebraska', '94163', 'Algeria');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (181, 181, '403 Kuhn Station', 'Schummhaven', 'Washington', '71588-0216', 'Dominica');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (182, 182, '691 Franz Mill', 'Wolfffurt', 'Idaho', '62989-8694', 'Pitcairn Islands');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (183, 183, '778 Schmidt Stream', 'Baumbachfort', 'Kansas', '21056-2741', 'Tokelau');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (184, 184, '63304 Grant Terrace Suite 989', 'Port Mariabury', 'Maryland', '74550', 'Serbia');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (185, 185, '60057 Stamm Keys Suite 818', 'East Jovanburgh', 'Virginia', '38972', 'Dominica');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (186, 186, '8931 Muller Track Suite 736', 'Rahsaanview', 'Connecticut', '36638', 'Slovakia (Slovak Republic)');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (187, 187, '951 Rafaela Branch', 'New Nikita', 'Montana', '69561-7276', 'Cote d\'Ivoire');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (188, 188, '8716 Rath Landing', 'East Rebeka', 'Connecticut', '16525-6830', 'Gambia');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (189, 189, '558 Ole Burgs Apt. 041', 'South Meaghan', 'Kansas', '88120', 'Saint Helena');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (190, 190, '603 Hettinger Plaza', 'Vancehaven', 'Vermont', '83302', 'Sweden');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (191, 191, '11765 Donnelly Expressway Suite 109', 'Port Nella', 'Connecticut', '07320', 'Liberia');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (192, 192, '92915 Wiley Island Suite 291', 'Lynchtown', 'Hawaii', '40717', 'Gambia');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (193, 193, '18462 Prosacco Station', 'Sandraside', 'NorthCarolina', '50313-0508', 'Italy');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (194, 194, '61793 Champlin Hollow', 'South Vicky', 'WestVirginia', '13206', 'Luxembourg');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (195, 195, '54686 Gene Tunnel', 'Giovannistad', 'Alabama', '46631', 'Wallis and Futuna');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (196, 196, '65375 Douglas Mills', 'Feeneytown', 'Louisiana', '16267-0463', 'Canada');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (197, 197, '23758 D\'Amore Ramp', 'Rempelfort', 'Maryland', '94654', 'Guernsey');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (198, 198, '72632 Wilkinson Overpass Apt. 102', 'Leannonland', 'Montana', '56352', 'France');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (199, 199, '0771 Kovacek Unions Apt. 155', 'New Andreaneton', 'SouthCarolina', '21695', 'Comoros');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (200, 200, '41562 Dickens Motorway Suite 084', 'Gaylordfurt', 'Nevada', '14519-6061', 'Djibouti');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (201, 201, '29724 Selmer Street', 'Moenmouth', 'Arizona', '10317-3485', 'Norway');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (202, 202, '24981 Osinski Island Apt. 342', 'Matteoside', 'Colorado', '67565-2009', 'Qatar');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (203, 203, '347 Cory Extension Apt. 144', 'O\'Keefestad', 'SouthDakota', '29143', 'Central African Republic');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (204, 204, '480 Jast Groves', 'Gerholdbury', 'Indiana', '90209', 'Russian Federation');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (205, 205, '8336 Feest Inlet', 'Loriview', 'Kentucky', '63953-5241', 'Mauritania');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (206, 206, '193 Carroll Fords Suite 468', 'Port Madaline', 'Arizona', '07125', 'Tuvalu');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (207, 207, '0822 Justice Square', 'Port Jewell', 'Florida', '14782', 'Bolivia');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (208, 208, '096 Jazmyne Rue', 'East Hillard', 'SouthDakota', '05793', 'Niger');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (209, 209, '077 Faustino Mission Suite 431', 'Bahringerbury', 'Missouri', '39462-8302', 'Armenia');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (210, 210, '3153 Rosalind Plains Suite 597', 'East Generalville', 'SouthDakota', '46810-6510', 'Haiti');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (211, 211, '6307 Sierra Mountain', 'Jerdestad', 'Nevada', '60191-7943', 'Senegal');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (212, 212, '550 Dominic Forge Apt. 423', 'East Gradyfurt', 'Hawaii', '50268-8431', 'Comoros');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (213, 213, '4995 McLaughlin Lake', 'Nicolasside', 'Illinois', '99265-2670', 'United States of America');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (214, 214, '8284 Hammes Station', 'North Emmitt', 'Pennsylvania', '60487', 'Finland');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (215, 215, '346 Romaguera Trace', 'Hellerport', 'Oregon', '50212', 'Sri Lanka');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (216, 216, '50797 Delphia Glens Suite 760', 'Noemimouth', 'Connecticut', '84138', 'Malaysia');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (217, 217, '4737 Greenfelder Loop', 'Port Viviane', 'Wisconsin', '40083', 'Japan');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (218, 218, '579 Klein Well Apt. 346', 'Gusikowskiville', 'Florida', '26022', 'Bolivia');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (219, 219, '616 Stiedemann Overpass Suite 577', 'Mosheborough', 'Iowa', '42692-2232', 'Heard Island and McDonald Islands');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (220, 220, '63361 Alivia Place Apt. 064', 'Lake Reannachester', 'Oregon', '28351', 'Moldova');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (221, 221, '633 Jaime Lock', 'Brennonside', 'Pennsylvania', '71505', 'Tanzania');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (222, 222, '94030 Grimes Trail Apt. 133', 'Jalynmouth', 'Florida', '32045-7413', 'Sudan');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (223, 223, '3072 Alysa Course Apt. 134', 'South Glenna', 'SouthDakota', '70082', 'Guatemala');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (224, 224, '582 Lora Route', 'West Damianview', 'Nebraska', '71460', 'Syrian Arab Republic');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (225, 225, '34388 Pagac Prairie Apt. 081', 'Maxieberg', 'RhodeIsland', '65327', 'United Arab Emirates');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (226, 226, '23859 Wehner Land Apt. 246', 'East Kaylie', 'Georgia', '30295', 'Slovenia');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (227, 227, '0016 Rosetta Park Apt. 874', 'South Germaine', 'California', '06320-1653', 'Korea');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (228, 228, '24895 Katelyn Villages Suite 242', 'South Darionton', 'SouthCarolina', '57551', 'Ethiopia');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (229, 229, '395 Giovanna Forges', 'Port Alanisburgh', 'District of Columbia', '69571', 'Netherlands Antilles');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (230, 230, '23908 Bailey Cove Apt. 407', 'Joaquinberg', 'Ohio', '71790', 'Ghana');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (231, 231, '834 Adelia Parkway', 'Turnerborough', 'Nebraska', '18495-7122', 'Taiwan');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (232, 232, '11216 Franecki Grove', 'East Sterlingbury', 'Connecticut', '24649-5232', 'Netherlands');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (233, 233, '220 Donnelly Plain Apt. 559', 'West Arvidchester', 'Washington', '45761-3244', 'Malta');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (234, 234, '339 Kris Glens Suite 146', 'New Cynthiahaven', 'Michigan', '26094', 'Reunion');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (235, 235, '3967 Gibson Shoals', 'Walshland', 'Hawaii', '43409', 'Burundi');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (236, 236, '7074 Reichert Pines Apt. 602', 'Shaniyastad', 'Delaware', '24475-2546', 'Ethiopia');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (237, 237, '6290 Hansen Junctions', 'Vincentborough', 'WestVirginia', '56253', 'Germany');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (238, 238, '912 Abigale Meadow', 'North Alethaburgh', 'Minnesota', '14728', 'Zambia');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (239, 239, '30313 Wilkinson Union Suite 484', 'Westborough', 'NewHampshire', '93474-7417', 'Jordan');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (240, 240, '52628 Jose Plaza', 'South Amiyaton', 'Montana', '65181-1108', 'Heard Island and McDonald Islands');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (241, 241, '8644 Wolff Village Suite 520', 'Schowalterstad', 'Delaware', '45065-7242', 'Liberia');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (242, 242, '9480 Jones Centers Suite 846', 'West Greg', 'Utah', '62003-0242', 'Canada');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (243, 243, '556 Ritchie Cliff', 'Daphneborough', 'Arkansas', '00675-5981', 'Montserrat');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (244, 244, '9652 Trenton Extension', 'Port Devante', 'California', '32590-7558', 'Norfolk Island');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (245, 245, '11336 Gladyce Orchard', 'Ardithstad', 'Utah', '37721', 'Finland');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (246, 246, '77178 Chelsea Vista Suite 680', 'Javontown', 'Montana', '22098-8485', 'Falkland Islands (Malvinas)');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (247, 247, '94278 Bernhard Squares Suite 163', 'South Lucie', 'Pennsylvania', '68057-1286', 'Tanzania');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (248, 248, '0462 Destin Streets Suite 799', 'Lake Dariana', 'Maryland', '73368-5719', 'Barbados');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (249, 249, '94574 Mann Avenue Suite 760', 'Lake Drakeside', 'Montana', '66213-4142', 'Northern Mariana Islands');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (250, 250, '22501 Margot Common', 'East Lempi', 'Georgia', '39821', 'Malaysia');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (251, 251, '9658 Teagan Rest', 'Veumstad', 'Alaska', '81593', 'Chad');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (252, 252, '6503 Hyatt Summit Apt. 067', 'West Ray', 'SouthCarolina', '44996', 'Saudi Arabia');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (253, 253, '482 Marty Tunnel Apt. 777', 'Adelleville', 'Delaware', '99548-3448', 'Benin');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (254, 254, '9905 Dibbert Ports Apt. 253', 'East Macy', 'Michigan', '16908-1094', 'Belize');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (255, 255, '10266 Ferry Ridges', 'South Hettie', 'Nevada', '01202-8939', 'Singapore');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (256, 256, '088 Veum Trail', 'East Aricstad', 'Indiana', '82841-2357', 'Namibia');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (257, 257, '780 Goyette Inlet', 'West Margueriteton', 'Hawaii', '38912-6884', 'Belgium');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (258, 258, '0764 Spinka Motorway', 'West Alberta', 'Iowa', '79114', 'Saint Kitts and Nevis');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (259, 259, '555 Bode Neck', 'South Roxanefort', 'Kentucky', '57589-2228', 'Wallis and Futuna');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (260, 260, '59457 Jerome Spur Suite 114', 'Anissaland', 'Wisconsin', '01000', 'Cocos (Keeling) Islands');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (261, 261, '2351 Shields Hill Apt. 402', 'Ashlynnside', 'Connecticut', '45305', 'Palestinian Territory');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (262, 262, '6028 Zakary Square', 'Lake Vicky', 'Nebraska', '44482', 'Morocco');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (263, 263, '62843 Janiya Turnpike Apt. 505', 'Aliciaport', 'Nevada', '03982-0726', 'Kyrgyz Republic');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (264, 264, '89405 Horace Drives Apt. 295', 'North Jeramy', 'Georgia', '01848-4146', 'Antarctica (the territory South of 60 deg S)');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (265, 265, '007 Saige Forge Apt. 798', 'South Luz', 'Alaska', '70474', 'Chad');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (266, 266, '10903 Callie Islands', 'Lake Ewald', 'Alaska', '13938-1855', 'Saint Vincent and the Grenadines');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (267, 267, '27161 Henri Dale', 'New Camyllefort', 'California', '18575-4874', 'Saint Martin');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (268, 268, '9761 Kub Landing', 'Granvillefurt', 'NewMexico', '75266', 'Trinidad and Tobago');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (269, 269, '956 West Springs', 'New Neldastad', 'Iowa', '50532-1369', 'Eritrea');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (270, 270, '416 Parisian Mission Suite 493', 'Adolphusside', 'Nebraska', '90707-9218', 'Isle of Man');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (271, 271, '978 Cordell Motorway Suite 992', 'New Burniceside', 'Wisconsin', '16982', 'Antarctica (the territory South of 60 deg S)');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (272, 272, '6164 Tromp Run Apt. 517', 'East Pascale', 'Maine', '59065', 'Singapore');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (273, 273, '1466 Bergstrom Fort Apt. 517', 'Destinburgh', 'Idaho', '05747-3885', 'Germany');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (274, 274, '458 Connelly Terrace Suite 309', 'Dietrichborough', 'Illinois', '80672-4906', 'Greece');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (275, 275, '51954 Yvette Lock', 'Chestertown', 'California', '39244', 'Brunei Darussalam');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (276, 276, '0079 Cynthia Tunnel Suite 843', 'North Lamar', 'Delaware', '68652', 'Czech Republic');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (277, 277, '458 Roy Port', 'Luraport', 'Michigan', '19500-3792', 'Svalbard & Jan Mayen Islands');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (278, 278, '5736 Greenfelder Crossroad Suite 177', 'South Stephon', 'Virginia', '78692', 'Barbados');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (279, 279, '0048 McCullough Harbors Apt. 666', 'North Groverton', 'Kentucky', '33585-5707', 'Singapore');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (280, 280, '47490 Zulauf Rapid', 'Lake Ollie', 'Delaware', '37687-0467', 'Peru');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (281, 281, '3645 Amy Walk', 'Roweport', 'Wisconsin', '07550-6714', 'Montserrat');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (282, 282, '63362 Brittany Plains', 'Lake William', 'Minnesota', '85530', 'Somalia');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (283, 283, '4011 Swift Street', 'East Delilahborough', 'Massachusetts', '33856-9900', 'Yemen');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (284, 284, '954 Damion Turnpike', 'West Margretland', 'Texas', '42188-5357', 'Bulgaria');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (285, 285, '77721 Gwen Centers', 'New Reytown', 'Massachusetts', '78764-2251', 'China');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (286, 286, '983 Vivien Walks', 'Jayceeshire', 'Connecticut', '51632', 'Saint Vincent and the Grenadines');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (287, 287, '404 Considine Lane Suite 754', 'Millerfurt', 'Hawaii', '74299', 'Thailand');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (288, 288, '50942 Mraz Tunnel Suite 855', 'Markside', 'Alabama', '20187-4022', 'Sri Lanka');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (289, 289, '159 Yasmine Street', 'Mallieburgh', 'Kentucky', '59680', 'Cocos (Keeling) Islands');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (290, 290, '130 Larson Drive', 'Lenniefurt', 'Alaska', '30857', 'Senegal');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (291, 291, '383 Shakira Orchard', 'Port Colin', 'Florida', '25894-8799', 'Gabon');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (292, 292, '6157 Cummings Wells', 'Peggieview', 'Colorado', '10560', 'Egypt');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (293, 293, '71853 Brain Harbor Suite 229', 'Lake Lacyview', 'Virginia', '92392', 'Guernsey');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (294, 294, '15542 Mariano Gardens', 'Okunevaside', 'Pennsylvania', '59094', 'Switzerland');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (295, 295, '320 Beer Crescent Suite 146', 'Vincenzafurt', 'NorthCarolina', '05097', 'Hong Kong');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (296, 296, '8898 Ward Creek', 'South Beatrice', 'Alabama', '41561-3649', 'Grenada');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (297, 297, '2862 Marvin Lights Apt. 978', 'Benniebury', 'Missouri', '25847-0794', 'Costa Rica');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (298, 298, '544 Durgan Run Apt. 927', 'Ricefort', 'Alaska', '88691', 'Hungary');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (299, 299, '978 Maia Parks Apt. 015', 'New Spencer', 'Kentucky', '26409-1963', 'Poland');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (300, 300, '675 Berge Radial', 'Brownfurt', 'Minnesota', '82140', 'Antigua and Barbuda');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (301, 301, '72566 Brayan Vista Suite 687', 'Conradville', 'Oklahoma', '06805-6784', 'Monaco');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (302, 302, '37922 Buster Locks Suite 739', 'Port Gretchen', 'Pennsylvania', '59045', 'Samoa');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (303, 303, '15182 Gleason Flats', 'Stromanstad', 'SouthCarolina', '09864', 'Guyana');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (304, 304, '0594 Gutkowski Union Suite 479', 'New Karlshire', 'Kentucky', '13357-2063', 'Bhutan');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (305, 305, '8141 Lucious Ranch Apt. 794', 'East Asa', 'Louisiana', '77566', 'Kuwait');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (306, 306, '59588 Roman Spring', 'Kolbyborough', 'NorthDakota', '37126-9389', 'Hungary');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (307, 307, '643 Aiden Rest Suite 613', 'South Madilyn', 'Mississippi', '85313-9315', 'Italy');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (308, 308, '2719 Josie Knoll', 'Manuelashire', 'Idaho', '20970-8738', 'Togo');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (309, 309, '05744 Maribel Branch Apt. 736', 'New Casimerfurt', 'California', '50312', 'United States of America');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (310, 310, '6781 Leonel Field', 'Mullertown', 'Mississippi', '47033-0595', 'Philippines');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (311, 311, '785 Muller Gardens Suite 996', 'Christinachester', 'NewHampshire', '80320', 'Thailand');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (312, 312, '336 April Road', 'South Noemie', 'Ohio', '46334-3393', 'Liberia');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (313, 313, '26606 Hansen Extension', 'Uptonside', 'NewMexico', '00681', 'Madagascar');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (314, 314, '962 Carlos Street Apt. 400', 'East Daphneystad', 'Oklahoma', '24985', 'Morocco');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (315, 315, '760 Claudie Pass Apt. 124', 'West Titoville', 'Louisiana', '36076-8011', 'Solomon Islands');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (316, 316, '07023 Moses Locks Suite 043', 'East Candaceport', 'Wisconsin', '73028', 'Benin');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (317, 317, '20961 Rosalinda Mall Apt. 624', 'West Hoyt', 'Florida', '85616', 'Comoros');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (318, 318, '312 Hahn Shore', 'South Reilly', 'Virginia', '83719-0199', 'Papua New Guinea');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (319, 319, '648 Gerhold Rapid Suite 988', 'New Eugene', 'Maryland', '53116', 'Ethiopia');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (320, 320, '743 Jammie Fields', 'South Jordytown', 'NorthCarolina', '07893', 'Saint Lucia');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (321, 321, '9718 Bailey Rapids Suite 052', 'East Sylvanport', 'Wyoming', '03467', 'Egypt');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (322, 322, '39912 Krista Light Suite 005', 'Ziemannside', 'Alaska', '72793-5085', 'Pakistan');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (323, 323, '91810 Lucio Gardens Suite 029', 'New Dedrickfurt', 'RhodeIsland', '28544', 'Turks and Caicos Islands');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (324, 324, '54390 Margret Flat Apt. 272', 'New Zoeyburgh', 'Minnesota', '61963-7379', 'Mozambique');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (325, 325, '10237 Elias Fall', 'Andreanneborough', 'Iowa', '02097-9772', 'American Samoa');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (326, 326, '2292 Considine Fort', 'Ernserberg', 'Florida', '11315-4188', 'Mozambique');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (327, 327, '7716 Dennis Ridge', 'Smithamside', 'Connecticut', '55156-3510', 'Qatar');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (328, 328, '8275 Garett Loaf Apt. 193', 'Lake Pete', 'Texas', '17877', 'Costa Rica');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (329, 329, '97611 Casper Square Suite 202', 'Lake Clare', 'District of Columbia', '54346-2617', 'Austria');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (330, 330, '510 King Flat', 'Daronhaven', 'Nevada', '33772', 'Madagascar');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (331, 331, '608 Hoeger Avenue Suite 196', 'Lake Newellfurt', 'Colorado', '30727-6338', 'Timor-Leste');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (332, 332, '2061 Elvis Island Suite 462', 'Jadenburgh', 'Ohio', '91417-2893', 'Romania');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (333, 333, '0922 Pagac Divide Suite 910', 'Bransonview', 'District of Columbia', '10431', 'Andorra');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (334, 334, '48677 Vince Lock', 'Lake Pinkberg', 'NewYork', '98226', 'Iraq');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (335, 335, '798 Lind Hollow Suite 325', 'Kenyattastad', 'Illinois', '55584', 'Zambia');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (336, 336, '03579 Kovacek Neck', 'O\'Harashire', 'Mississippi', '92577-5097', 'Brunei Darussalam');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (337, 337, '908 Waters Lakes Suite 863', 'Rhettmouth', 'Colorado', '75937', 'Kuwait');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (338, 338, '21473 Schultz Knoll Suite 918', 'Lemuelbury', 'Pennsylvania', '39688-7932', 'Tonga');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (339, 339, '66335 Herman River', 'East Stellaport', 'Alabama', '88365-6082', 'Costa Rica');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (340, 340, '0781 Becker Isle Apt. 151', 'Ratkeshire', 'NewMexico', '21785', 'Oman');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (341, 341, '75906 Mike Points Apt. 760', 'Cronaview', 'Florida', '68348', 'Nauru');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (342, 342, '05088 Deondre Villages Apt. 942', 'Ameliaview', 'Mississippi', '27107', 'Bulgaria');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (343, 343, '9233 Roberts Islands Apt. 032', 'Mylenestad', 'Oklahoma', '78149', 'Qatar');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (344, 344, '8365 Natalie Trail Suite 929', 'Jacklynshire', 'Virginia', '79154', 'India');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (345, 345, '931 Johnston Stream Apt. 000', 'West Jabarihaven', 'RhodeIsland', '15771', 'Greece');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (346, 346, '5916 Brigitte Ridge', 'East Kristaview', 'Alabama', '70710-3223', 'Kyrgyz Republic');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (347, 347, '8396 Prohaska View Suite 301', 'Ritchiefurt', 'Maryland', '26186-2121', 'South Georgia and the South Sandwich Islands');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (348, 348, '87668 Jaskolski Pine Suite 377', 'South Huldaburgh', 'Florida', '79587-4486', 'Sao Tome and Principe');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (349, 349, '73270 Tromp Ports Apt. 165', 'East Sidney', 'Hawaii', '00229-5447', 'Congo');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (350, 350, '16889 Dietrich Views', 'East Mina', 'Arkansas', '24767-8059', 'Bahrain');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (351, 351, '63773 Kristofer Views Apt. 855', 'Coyville', 'Texas', '56418-8818', 'Korea');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (352, 352, '58386 Tromp Glen', 'Nitzschetown', 'Connecticut', '60130', 'Bouvet Island (Bouvetoya)');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (353, 353, '6033 Alfreda Mall', 'West Brettborough', 'Wyoming', '31461-3505', 'Albania');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (354, 354, '11931 Ella Spring Suite 434', 'East Dianaton', 'Minnesota', '65708-7792', 'Liberia');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (355, 355, '0185 Larson Loaf Apt. 062', 'Port Marcelina', 'Oklahoma', '00562-2706', 'Indonesia');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (356, 356, '9120 Durgan Plaza Suite 701', 'New Nicklaus', 'NewYork', '55843-6619', 'Martinique');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (357, 357, '66715 Robel Creek Suite 694', 'West Athenafort', 'Florida', '33375-7165', 'Ireland');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (358, 358, '373 Gus Trail', 'Hayesside', 'Washington', '75045-0495', 'Gabon');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (359, 359, '67061 Leffler Mountain', 'O\'Konchester', 'Arkansas', '67223', 'Tajikistan');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (360, 360, '24690 Kemmer Mews', 'Gaylehaven', 'Massachusetts', '38037-9136', 'Hungary');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (361, 361, '605 Rath Fords', 'Reedberg', 'NewMexico', '93016-3538', 'Gibraltar');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (362, 362, '954 Sporer Trafficway Suite 591', 'Rodriguezside', 'Colorado', '20355-8379', 'Ireland');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (363, 363, '20987 Zane Canyon Apt. 330', 'Jarrellmouth', 'Wyoming', '61133-5516', 'Bolivia');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (364, 364, '398 Abdiel Grove Apt. 819', 'New Alberta', 'Alabama', '46529-7935', 'South Africa');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (365, 365, '3506 Oberbrunner Brooks', 'Reichertton', 'Wisconsin', '51625', 'Rwanda');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (366, 366, '16414 Keebler Cliff Apt. 916', 'West Bartholome', 'Michigan', '32278', 'Lithuania');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (367, 367, '0404 Orn Motorway', 'Kingland', 'Washington', '14307', 'Netherlands Antilles');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (368, 368, '258 Pfannerstill Views Suite 923', 'Lillianside', 'Illinois', '29769', 'Holy See (Vatican City State)');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (369, 369, '503 Fannie Overpass', 'Larsonport', 'Oklahoma', '57941', 'Samoa');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (370, 370, '505 Alec Prairie', 'South Mayra', 'Connecticut', '84194-7723', 'Sri Lanka');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (371, 371, '683 Grady Fort Suite 503', 'Pourosland', 'California', '90001', 'Azerbaijan');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (372, 372, '929 Veum Ridge Apt. 872', 'Port Adeleside', 'Texas', '57498-6823', 'Singapore');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (373, 373, '87025 Camden Pine', 'Shainaville', 'Pennsylvania', '71691-5296', 'Hong Kong');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (374, 374, '2511 Littel Locks', 'Tremainefurt', 'Iowa', '99162-9363', 'Guyana');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (375, 375, '0359 Trenton Orchard', 'Bernierstad', 'Tennessee', '33517', 'Hong Kong');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (376, 376, '30761 Roberts Stream Apt. 384', 'Selmermouth', 'Arkansas', '71390', 'Canada');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (377, 377, '704 McKenzie Lock Apt. 879', 'New Marquisborough', 'Illinois', '16785', 'China');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (378, 378, '3612 Darwin Club', 'Tyramouth', 'Minnesota', '94087', 'Liberia');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (379, 379, '87461 Kerluke Turnpike', 'Wolffshire', 'Minnesota', '84590', 'Netherlands Antilles');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (380, 380, '9289 Bogan Union Apt. 815', 'East Bryon', 'Tennessee', '34208-9128', 'United States of America');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (381, 381, '1262 Kamren Loop', 'North Clifford', 'Texas', '96186-0941', 'Luxembourg');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (382, 382, '1809 Karson Drive Suite 738', 'Port Davonmouth', 'Missouri', '22833', 'Niue');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (383, 383, '3442 Kaitlin Island', 'South Oswaldoville', 'Kansas', '17413', 'Cambodia');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (384, 384, '527 Tony Brooks', 'North Quentin', 'Oregon', '80557', 'Jersey');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (385, 385, '00408 Santa Overpass Apt. 798', 'Penelopechester', 'Alabama', '85688-0937', 'Liberia');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (386, 386, '4811 Thaddeus Extensions', 'Cristburgh', 'Florida', '85308', 'Jersey');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (387, 387, '2924 Aufderhar Fall Apt. 493', 'Alexandrinetown', 'NewMexico', '73665-6895', 'Eritrea');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (388, 388, '707 Arden Highway Apt. 459', 'East Suzanne', 'Connecticut', '13944-9376', 'Kyrgyz Republic');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (389, 389, '148 Paula Estates Apt. 734', 'East Odessa', 'Oklahoma', '16899-8745', 'Saint Pierre and Miquelon');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (390, 390, '47454 Weimann Parkway', 'West Nadia', 'Colorado', '15352', 'Turkmenistan');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (391, 391, '55534 Jarret Street', 'New Onie', 'WestVirginia', '87455-0355', 'Moldova');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (392, 392, '434 Kassulke Estates Apt. 575', 'West Tesschester', 'Maine', '05339', 'Guyana');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (393, 393, '33663 Farrell Trace', 'Weimannhaven', 'Virginia', '11496', 'Bulgaria');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (394, 394, '04238 Lowe Squares Apt. 645', 'Lake Murphyville', 'Illinois', '77048', 'Libyan Arab Jamahiriya');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (395, 395, '3297 Derek Flat', 'Emardmouth', 'SouthCarolina', '55698', 'Malawi');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (396, 396, '031 McLaughlin Overpass Apt. 276', 'Nienowbury', 'Delaware', '77867', 'Syrian Arab Republic');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (397, 397, '23043 Giuseppe Island Suite 802', 'North Estelle', 'NorthDakota', '20453-0700', 'Kenya');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (398, 398, '12655 West Crossroad Suite 898', 'Reinholdmouth', 'Kansas', '38736', 'Czech Republic');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (399, 399, '9326 Mayert Spur', 'Dietrichstad', 'Oregon', '60475-6069', 'Malta');
INSERT INTO `ADDRESS` (`Address_id`, `Customer_id`, `Street`, `City`, `State`, `Zipcode`, `Country`) VALUES (400, 400, '829 Morissette Hills Apt. 127', 'East Mathildechester', 'Hawaii', '89508-7668', 'Taiwan');


