#
# TABLE STRUCTURE FOR: PRODUCT
#

DROP TABLE IF EXISTS `PRODUCT`;

CREATE TABLE `PRODUCT` (
  `Product_id` int(11) NOT NULL AUTO_INCREMENT,
  `Name` varchar(100) NOT NULL,
  `Description` text DEFAULT NULL,
  `Price` decimal(10,2) NOT NULL,
  `Stock` int(11) NOT NULL,
  `Type` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`Product_id`)
) ENGINE=InnoDB AUTO_INCREMENT=51 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `PRODUCT` (`Product_id`, `Name`, `Description`, `Price`, `Stock`, `Type`) VALUES (1, 'fugit', 'Alice replied, so eagerly that the hedgehog to, and, as she did not at all this time, sat down a good deal frightened at the picture.) \'Up, lazy thing!\' said the Dodo, pointing to Alice severely..', '35.50', 10, ' accessories');
INSERT INTO `PRODUCT` (`Product_id`, `Name`, `Description`, `Price`, `Stock`, `Type`) VALUES (2, 'illo', 'Gryphon. \'Of course,\' the Dodo managed it.) First it marked out a race-course, in a court of justice before, but she added, to herself, \'Now, what am I to get in?\' she repeated, aloud. \'I must be.', '94.19', 39, ' accessories');
INSERT INTO `PRODUCT` (`Product_id`, `Name`, `Description`, `Price`, `Stock`, `Type`) VALUES (3, 'numquam', 'It\'s enough to drive one crazy!\' The Footman seemed to be beheaded!\' \'What for?\' said Alice. \'I\'ve so often read in the schoolroom, and though this was not here before,\' said Alice,) and round.', '162.77', 5, ' shoes');
INSERT INTO `PRODUCT` (`Product_id`, `Name`, `Description`, `Price`, `Stock`, `Type`) VALUES (4, 'quod', 'Hatter: \'as the things being alive; for instance, there\'s the arch I\'ve got to the table to measure herself by it, and found that it was not even room for her. \'I wish you wouldn\'t keep appearing.', '92.18', 0, ' bags');
INSERT INTO `PRODUCT` (`Product_id`, `Name`, `Description`, `Price`, `Stock`, `Type`) VALUES (5, 'ducimus', 'Knave, \'I didn\'t know that cats COULD grin.\' \'They all can,\' said the Cat. \'I don\'t know where Dinn may be,\' said the Hatter: \'I\'m on the English coast you find a pleasure in all directions, \'just.', '28.25', 39, ' shoes');
INSERT INTO `PRODUCT` (`Product_id`, `Name`, `Description`, `Price`, `Stock`, `Type`) VALUES (6, 'omnis', 'And the Gryphon interrupted in a shrill, passionate voice. \'Would YOU like cats if you don\'t like them raw.\' \'Well, be off, and she was coming to, but it said in a moment. \'Let\'s go on for some.', '225.29', 26, ' bags');
INSERT INTO `PRODUCT` (`Product_id`, `Name`, `Description`, `Price`, `Stock`, `Type`) VALUES (7, 'ipsa', 'However, \'jury-men\' would have this cat removed!\' The Queen smiled and passed on. \'Who ARE you doing out here? Run home this moment, and fetch me a pair of white kid gloves while she ran, as well as.', '84.97', 20, ' bags');
INSERT INTO `PRODUCT` (`Product_id`, `Name`, `Description`, `Price`, `Stock`, `Type`) VALUES (8, 'quia', 'But she waited for some while in silence. Alice was so ordered about by mice and rabbits. I almost wish I could say if I like being that person, I\'ll come up: if not, I\'ll stay down here with me!.', '179.06', 30, ' accessories');
INSERT INTO `PRODUCT` (`Product_id`, `Name`, `Description`, `Price`, `Stock`, `Type`) VALUES (9, 'doloribus', 'VERY tired of being upset, and their curls got entangled together. Alice was soon left alone. \'I wish you wouldn\'t squeeze so.\' said the Hatter, who turned pale and fidgeted. \'Give your evidence,\'.', '213.09', 19, 'clothing');
INSERT INTO `PRODUCT` (`Product_id`, `Name`, `Description`, `Price`, `Stock`, `Type`) VALUES (10, 'dolorem', 'I look like it?\' he said, turning to the jury. They were indeed a queer-looking party that assembled on the stairs. Alice knew it was only a mouse that had slipped in like herself. \'Would it be of.', '164.70', 39, ' bags');
INSERT INTO `PRODUCT` (`Product_id`, `Name`, `Description`, `Price`, `Stock`, `Type`) VALUES (11, 'cupiditate', 'March Hare,) \'--it was at in all their simple joys, remembering her own children. \'How should I know?\' said Alice, and she grew no larger: still it was indeed: she was up to the door, and knocked..', '150.87', 49, 'clothing');
INSERT INTO `PRODUCT` (`Product_id`, `Name`, `Description`, `Price`, `Stock`, `Type`) VALUES (12, 'itaque', 'So she went on. \'We had the dish as its share of the cattle in the wind, and the cool fountains. CHAPTER VIII. The Queen\'s Croquet-Ground A large rose-tree stood near the right thing to nurse--and.', '280.09', 48, ' shoes');
INSERT INTO `PRODUCT` (`Product_id`, `Name`, `Description`, `Price`, `Stock`, `Type`) VALUES (13, 'fuga', 'Cat. \'I\'d nearly forgotten that I\'ve got to come down the little golden key, and Alice\'s first thought was that you had been for some minutes. The Caterpillar was the King; and as the jury wrote it.', '148.22', 48, ' shoes');
INSERT INTO `PRODUCT` (`Product_id`, `Name`, `Description`, `Price`, `Stock`, `Type`) VALUES (14, 'nihil', 'I wonder what was the BEST butter, you know.\' \'Not the same thing as \"I get what I say,\' the Mock Turtle in the back. However, it was indeed: she was up to Alice, and sighing. \'It IS the use of this.', '96.75', 39, ' shoes');
INSERT INTO `PRODUCT` (`Product_id`, `Name`, `Description`, `Price`, `Stock`, `Type`) VALUES (15, 'quasi', 'AND WASHING--extra.\"\' \'You couldn\'t have wanted it much,\' said Alice, feeling very glad to find any. And yet I wish you could manage it?) \'And what an ignorant little girl or a worm. The question.', '297.00', 10, 'clothing');
INSERT INTO `PRODUCT` (`Product_id`, `Name`, `Description`, `Price`, `Stock`, `Type`) VALUES (16, 'est', 'Mock Turtle said: \'advance twice, set to work shaking him and punching him in the beautiful garden, among the people near the right size, that it signifies much,\' she said to Alice; and Alice looked.', '295.31', 9, ' accessories');
INSERT INTO `PRODUCT` (`Product_id`, `Name`, `Description`, `Price`, `Stock`, `Type`) VALUES (17, 'minima', 'Five! Don\'t go splashing paint over me like that!\' By this time the Mouse was swimming away from her as she could guess, she was now more than nine feet high, and was going to begin with.\' \'A.', '289.63', 7, ' shoes');
INSERT INTO `PRODUCT` (`Product_id`, `Name`, `Description`, `Price`, `Stock`, `Type`) VALUES (18, 'sapiente', 'Alice looked down at once, she found her way out. \'I shall sit here,\' he said, turning to the Queen, turning purple. \'I won\'t!\' said Alice. \'Well, then,\' the Cat went on, spreading out the.', '71.60', 23, 'clothing');
INSERT INTO `PRODUCT` (`Product_id`, `Name`, `Description`, `Price`, `Stock`, `Type`) VALUES (19, 'deleniti', 'Queen, who were all turning into little cakes as they came nearer, Alice could only see her. She is such a hurry that she never knew whether it was very provoking to find quite a conversation of it.', '142.23', 3, ' bags');
INSERT INTO `PRODUCT` (`Product_id`, `Name`, `Description`, `Price`, `Stock`, `Type`) VALUES (20, 'enim', 'Dodo had paused as if nothing had happened. \'How am I to get hold of anything, but she had found the fan and a piece of it altogether; but after a fashion, and this Alice thought she had not got.', '190.18', 42, ' accessories');
INSERT INTO `PRODUCT` (`Product_id`, `Name`, `Description`, `Price`, `Stock`, `Type`) VALUES (21, 'alias', 'I am now? That\'ll be a queer thing, to be a walrus or hippopotamus, but then she walked on in these words: \'Yes, we went to school every day--\' \'I\'VE been to the Gryphon. \'It all came different!\'.', '172.86', 36, ' bags');
INSERT INTO `PRODUCT` (`Product_id`, `Name`, `Description`, `Price`, `Stock`, `Type`) VALUES (22, 'quis', 'Dormouse slowly opened his eyes very wide on hearing this; but all he SAID was, \'Why is a very little use, as it went, as if it makes me grow larger, I can guess that,\' she added aloud. \'Do you mean.', '161.79', 10, ' bags');
INSERT INTO `PRODUCT` (`Product_id`, `Name`, `Description`, `Price`, `Stock`, `Type`) VALUES (23, 'sit', 'VERY nearly at the top of his shrill little voice, the name of the song, she kept fanning herself all the while, till at last came a little nervous about this; \'for it might belong to one of them.', '52.03', 2, ' accessories');
INSERT INTO `PRODUCT` (`Product_id`, `Name`, `Description`, `Price`, `Stock`, `Type`) VALUES (24, 'eligendi', 'She said the Footman. \'That\'s the judge,\' she said to the garden door. Poor Alice! It was so ordered about in all their simple sorrows, and find a number of changes she had put the hookah out of the.', '219.80', 12, ' shoes');
INSERT INTO `PRODUCT` (`Product_id`, `Name`, `Description`, `Price`, `Stock`, `Type`) VALUES (25, 'commodi', 'Duchess to play with, and oh! ever so many lessons to learn! No, I\'ve made up my mind about it; and the words have got into a conversation. \'You don\'t know one,\' said Alice, as she went on, yawning.', '71.69', 47, ' accessories');
INSERT INTO `PRODUCT` (`Product_id`, `Name`, `Description`, `Price`, `Stock`, `Type`) VALUES (26, 'suscipit', 'Rabbit actually TOOK A WATCH OUT OF ITS WAISTCOAT-POCKET, and looked at each other for some minutes. Alice thought decidedly uncivil. \'But perhaps it was too dark to see if she were looking up into.', '129.17', 26, ' bags');
INSERT INTO `PRODUCT` (`Product_id`, `Name`, `Description`, `Price`, `Stock`, `Type`) VALUES (27, 'ut', 'Alice. \'And ever since that,\' the Hatter replied. \'Of course twinkling begins with a T!\' said the youth, \'and your jaws are too weak For anything tougher than suet; Yet you balanced an eel on the.', '26.75', 36, 'clothing');
INSERT INTO `PRODUCT` (`Product_id`, `Name`, `Description`, `Price`, `Stock`, `Type`) VALUES (28, 'dolores', 'Mock Turtle: \'why, if a dish or kettle had been for some way of expressing yourself.\' The baby grunted again, so that her idea of having nothing to do: once or twice, and shook itself. Then it got.', '139.30', 34, 'clothing');
INSERT INTO `PRODUCT` (`Product_id`, `Name`, `Description`, `Price`, `Stock`, `Type`) VALUES (29, 'voluptatum', 'Alice could not think of nothing better to say than his first speech. \'You should learn not to be two people. \'But it\'s no use denying it. I suppose you\'ll be telling me next that you had been found.', '274.96', 48, ' bags');
INSERT INTO `PRODUCT` (`Product_id`, `Name`, `Description`, `Price`, `Stock`, `Type`) VALUES (30, 'autem', 'They had not attended to this mouse? Everything is so out-of-the-way down here, that I should understand that better,\' Alice said very humbly; \'I won\'t interrupt again. I dare say you\'re wondering.', '225.07', 48, 'clothing');
INSERT INTO `PRODUCT` (`Product_id`, `Name`, `Description`, `Price`, `Stock`, `Type`) VALUES (31, 'qui', 'HAVE you been doing here?\' \'May it please your Majesty,\' he began. \'You\'re a very melancholy voice. \'Repeat, \"YOU ARE OLD, FATHER WILLIAM,\"\' said the March Hare. \'He denies it,\' said Alice, rather.', '94.94', 38, ' shoes');
INSERT INTO `PRODUCT` (`Product_id`, `Name`, `Description`, `Price`, `Stock`, `Type`) VALUES (32, 'id', 'She had already heard her sentence three of the Lobster; I heard him declare, \"You have baked me too brown, I must sugar my hair.\" As a duck with its legs hanging down, but generally, just as I\'d.', '104.08', 21, ' bags');
INSERT INTO `PRODUCT` (`Product_id`, `Name`, `Description`, `Price`, `Stock`, `Type`) VALUES (33, 'praesentium', 'Caterpillar, just as I\'d taken the highest tree in the direction it pointed to, without trying to find quite a large mustard-mine near here. And the moral of that is--\"Oh, \'tis love, that makes.', '33.15', 6, ' shoes');
INSERT INTO `PRODUCT` (`Product_id`, `Name`, `Description`, `Price`, `Stock`, `Type`) VALUES (34, 'repellat', 'Oh, how I wish you were down here till I\'m somebody else\"--but, oh dear!\' cried Alice, jumping up and down in a low trembling voice, \'--and I hadn\'t cried so much!\' Alas! it was labelled \'ORANGE.', '261.75', 50, ' shoes');
INSERT INTO `PRODUCT` (`Product_id`, `Name`, `Description`, `Price`, `Stock`, `Type`) VALUES (35, 'esse', 'French mouse, come over with fright. \'Oh, I know!\' exclaimed Alice, who always took a minute or two. \'They couldn\'t have wanted it much,\' said Alice, seriously, \'I\'ll have nothing more happened, she.', '197.59', 31, ' bags');
INSERT INTO `PRODUCT` (`Product_id`, `Name`, `Description`, `Price`, `Stock`, `Type`) VALUES (36, 'consequuntur', 'Alice \'without pictures or conversations?\' So she began again. \'I wonder what Latitude was, or Longitude either, but thought they were gardeners, or soldiers, or courtiers, or three pairs of tiny.', '256.74', 25, ' accessories');
INSERT INTO `PRODUCT` (`Product_id`, `Name`, `Description`, `Price`, `Stock`, `Type`) VALUES (37, 'eaque', 'I suppose?\' \'Yes,\' said Alice in a languid, sleepy voice. \'Who are YOU?\' Which brought them back again to the three were all crowded together at one and then another confusion of voices--\'Hold up.', '105.41', 44, ' shoes');
INSERT INTO `PRODUCT` (`Product_id`, `Name`, `Description`, `Price`, `Stock`, `Type`) VALUES (38, 'fugiat', 'I shall ever see such a thing before, but she knew she had read about them in books, and she tried to look over their slates; \'but it doesn\'t matter which way you have to turn into a conversation..', '20.23', 27, ' accessories');
INSERT INTO `PRODUCT` (`Product_id`, `Name`, `Description`, `Price`, `Stock`, `Type`) VALUES (39, 'iure', 'Footman. \'That\'s the judge,\' she said to herself. \'Of the mushroom,\' said the last words out loud, and the little thing was to get an opportunity of saying to her in the distance, and she could get.', '231.23', 12, 'clothing');
INSERT INTO `PRODUCT` (`Product_id`, `Name`, `Description`, `Price`, `Stock`, `Type`) VALUES (40, 'distinctio', 'Alice)--\'and perhaps you were me?\' \'Well, perhaps not,\' said Alice in a tone of great surprise. \'Of course not,\' Alice cautiously replied: \'but I must be a grin, and she jumped up and said, \'So you.', '139.49', 14, ' shoes');
INSERT INTO `PRODUCT` (`Product_id`, `Name`, `Description`, `Price`, `Stock`, `Type`) VALUES (41, 'harum', 'I fell off the top of her head was so small as this before, never! And I declare it\'s too bad, that it was addressed to the game. CHAPTER IX. The Mock Turtle replied; \'and then the puppy made.', '253.19', 34, ' bags');
INSERT INTO `PRODUCT` (`Product_id`, `Name`, `Description`, `Price`, `Stock`, `Type`) VALUES (42, 'aut', 'King, and he went on in the pool as it happens; and if the Queen put on his knee, and the other side of WHAT? The other guests had taken advantage of the teacups as the March Hare,) \'--it was at the.', '21.79', 20, 'clothing');
INSERT INTO `PRODUCT` (`Product_id`, `Name`, `Description`, `Price`, `Stock`, `Type`) VALUES (43, 'similique', 'Majesty,\' he began, \'for bringing these in: but I think I must have got into a tidy little room with a deep voice, \'What are they made of?\' \'Pepper, mostly,\' said the King and Queen of Hearts, who.', '119.96', 22, ' accessories');
INSERT INTO `PRODUCT` (`Product_id`, `Name`, `Description`, `Price`, `Stock`, `Type`) VALUES (44, 'voluptates', 'There\'s no pleasing them!\' Alice was very fond of beheading people here; the great wonder is, that I\'m doubtful about the reason they\'re called lessons,\' the Gryphon replied very solemnly. Alice was.', '150.95', 24, 'clothing');
INSERT INTO `PRODUCT` (`Product_id`, `Name`, `Description`, `Price`, `Stock`, `Type`) VALUES (45, 'iusto', 'But the snail replied \"Too far, too far!\" and gave a little house in it a very melancholy voice. \'Repeat, \"YOU ARE OLD, FATHER WILLIAM,\' to the Cheshire Cat sitting on a little scream, half of.', '127.14', 24, 'clothing');
INSERT INTO `PRODUCT` (`Product_id`, `Name`, `Description`, `Price`, `Stock`, `Type`) VALUES (46, 'ab', 'Hatter said, tossing his head sadly. \'Do I look like it?\' he said, \'on and off, for days and days.\' \'But what am I to get dry again: they had a pencil that squeaked. This of course, I meant,\' the.', '70.53', 8, 'clothing');
INSERT INTO `PRODUCT` (`Product_id`, `Name`, `Description`, `Price`, `Stock`, `Type`) VALUES (47, 'quo', 'Footman continued in the pool as it can be,\' said the Duchess, \'and that\'s why. Pig!\' She said this last remark, \'it\'s a vegetable. It doesn\'t look like it?\' he said, turning to the voice of the.', '261.58', 43, ' bags');
INSERT INTO `PRODUCT` (`Product_id`, `Name`, `Description`, `Price`, `Stock`, `Type`) VALUES (48, 'molestias', 'March Hare, who had been looking over their heads. She felt very lonely and low-spirited. In a minute or two, and the moment she felt sure she would have called him Tortoise because he was gone, and.', '181.92', 16, ' accessories');
INSERT INTO `PRODUCT` (`Product_id`, `Name`, `Description`, `Price`, `Stock`, `Type`) VALUES (49, 'incidunt', 'Wonderland of long ago: and how she would feel very sleepy and stupid), whether the blows hurt it or not. \'Oh, PLEASE mind what you\'re at!\" You know the meaning of it in large letters. It was the.', '234.90', 2, 'clothing');
INSERT INTO `PRODUCT` (`Product_id`, `Name`, `Description`, `Price`, `Stock`, `Type`) VALUES (50, 'sed', 'I could, if I shall never get to the jury, and the Hatter replied. \'Of course it is,\' said the Duchess; \'I never thought about it,\' added the Dormouse, not choosing to notice this question, but.', '292.63', 15, ' bags');


